[WebRTC Bench] Improve stats, add latency measuremen
elixir-webrtc/bench pull request #3
Opened 2024-05-17 07:15 UTC by LVala

2024-05-20 14:12 UTC, mickel8 requested changes

2024-05-20 14:12 UTC, mickel8 commented on webrtc_bench/scripts/latency.exs
> +# "#{type} #{timestamp_in_ms} #{latency_in_ms}" split by newlines
Can we write what this script does, how to run it, and how to generate data for it? And that `type`  is one of "pc" "dtls" or "ice"?

2024-05-20 14:19 UTC, LVala commented on webrtc_bench/scripts/latency.exs
> +# "#{type} #{timestamp_in_ms} #{latency_in_ms}" split by newlines
I don't expect anyone else to use this script, you cannot generate the data for it unless you modify the benchmark code itself. I don't expect anyone to use it except for me, I can make a gist out of it if you don't want it here.

2024-05-20 14:24 UTC, LVala commented on webrtc_bench/scripts/latency.exs
> +# "#{type} #{timestamp_in_ms} #{latency_in_ms}" split by newlines
That's what I did.

2024-05-21 10:03 UTC, mickel8 approved these changes

2024-05-21 10:11 UTC, merged